MusicSchool/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/contactus', function () {
    return view('contactus');
});

Route::get('/aboutus', function () {
    return view('aboutus');
});

// Authetication
Route::get('/login', ['as'=>'login', 'uses'=>'AuthController@login']);
Route::get('/logout', ['as'=> 'logout', 'uses'=> 'AuthController@logout']);
Route::post('/handleLogin', ['as'=>'handleLogin', 'uses'=>'AuthController@handleLogin']);

// Member Portal
Route::resource('/users', 'UserController', ['Only'=> ['create', 'store']]);
Route::get('/register', 'UserController@create');   
Route::resource('/profile/edit', 'UserController', ['Only'=> ['edit', 'update']]);

Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', ['as'=> 'home', 'uses'=> 'UserController@home']);
	Route::get('/profile', ['as'=>'profile', 'uses'=> 'UserController@profile']); 
    Route::get('/profile/edit', ['as'=>'profile', 'uses'=> 'UserController@profileEdit']);
	Route::post('handleProfileUpdate', ['as'=>'handleProfileUpdate', 'uses'=>'UserController@handleProfileUpdate']);
});

// Lesson
Route::get('/lesson', 'LessonController@listRec');
Route::get('/lesson/singingclass', 'LessonController@listSingingClasses');
Route::get('/lesson/classespiano', 'LessonController@listPianoClasses');
Route::get('/lesson/classesdrums', 'LessonController@listDrumsClasses');
Route::get('/lesson/classesmusictheory', 'LessonController@listMusicTheoryClasses');
Route::resource('/lesson/enrollment', 'LessonController',['Only'=> ['create', 'store']]);
//Route::post('/lesson/handleEnrollment', ['as'=>'handleEnrollment', 'uses'=>'LessonController@handleEnrollment']);
Route::get('/lesson/apply', ['as'=> 'apply', 'uses'=> 'UserController@applyLessons']);
Route::patch('/lesson/applyHandle/{applyHandle}', ['as'=> 'applyHandle', 'uses'=> 'UserController@applyHandle']);

// Career
Route::get('/career', 'CareerController@recruit');




// For Release 2

// student part

Route::post('/student/handleFeedback', ['as'=>'handleFeedback', 'uses'=>'UserController@handleFeedback']);
Route::get('/student/historyMarks/feedbackToTeacher', function () {
    return view('users.student.feedbackToTeacher');
});
Route::group(['middleware' => 'auth'], function() {
    Route::get('/student/hireInstrument', function () {
        return view('users.student.hireInstrument');
    });
    Route::get('/student/historyMarks', ['as'=> 'historyMarks', 'uses'=> 'UserController@historyMarks']);
    Route::resource('/student/query-instrumentlist', "InstrumentController@query");
    Route::resource('/student/query-hireInstrument', "InstrumentController@hireInstrument");
});

// teachers part
Route::get('/teachers/myTimetable', function () {
    return view('users.teacher.myTimetable');
});
Route::get('/teachers/myTimetable/timetableArrangement', function () {
    return view('users.teacher.timetableArrangement');
});
Route::get('/teacher/mailBox', function () {
    return view('users.teacher.mailBox');
});

// admin part

Route::group(['middleware' => 'auth'], function() {
    Route::get('/admin', ['as'=> 'home', 'uses'=> 'UserController@home']);
    Route::get('/admin/instrumentManagement', "AdminController@viewInstruments");
    Route::post('/admin/instrumentManagement', ['as'=> 'addNewInstruments', 'uses'=>'AdminController@addNewInstruments']);
    Route::get('/admin/lessonArrangement', function () {
        return view('users.admin.lessonArrangement');
    });
    Route::get('/admin/enrollmentArrangement', "AdminController@enrollmentArrangement");
    Route::get('/admin/enrollmentArrangement/edit', function () {
        return view('users.admin.editEnrollmentForm');
    });
    Route::get('/admin/roomArrangement', function () {
        return view('users.admin.roomArrangement');
    });
    Route::get('/admin/mailBox', function () {
        return view('users.admin.mailBox');
    });

    Route::get('/admin/crewManagement/teachers/view', 'AdminController@viewTeachers');
    Route::get('/admin/crewManagement/teachers/add', function () {
        return view('users.admin.crewManagement.teachers.add');
    });
    Route::get('/admin/crewManagement/teachers/edit', function () {
        return view('users.admin.crewManagement.teachers.edit');
    });
    Route::get('/admin/crewManagement/teachers/viewFeedback', function () {
        return view('users.admin.crewManagement.teachers.viewFeedback');
    });

    Route::get('/admin/crewManagement/students/view', 'AdminController@viewStudents');
    Route::get('/admin/crewManagement/students/add', function () {
        return view('users.admin.crewManagement.students.add');
    });
    Route::get('/admin/crewManagement/students/edit', function () {
        return view('users.admin.crewManagement.students.edit');
    });

});

// owner part
Route::get('/owner', function () {
    return view('users.owner.home');
});Route::get('/owner/mailBox', function () {
    return view('users.owner.mailBox');
});
Route::get('/owner/mailHyperlink', function () {
    return view('users.owner.mailHyperlink');
});
Route::get('/owner/makeAnnouncement', function () {
    return view('users.owner.makeAnnouncement');
});

MusicSchool/app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\TeacherInfo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use App\Enrollment;
use App\StudentInfo;
use Carbon\Carbon;

/**
 *  The LessonController class performs all the backend activities related to lesson records.
 */
class LessonController extends Controller
{
    /**
     * This method displays a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Not planned to implement
    }

    /**
     * This method shows the form for enrolling to a new lesson.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->role == "student") {
            return view('/lesson/enrollment');
        } else{
            echo "Cannot enroll, because you are not student";
            //return back();
        }
    }

    /**
     * This method stores a new lesson enrollment.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userId = Auth::user()->id;
        $student = StudentInfo::where('userId', $userId)->first();

        // Create user login
        $data = $request->all();
        $enrollment = new Enrollment;


        // check the ending date is bigger than starting date
        if(($data['startingDate'] <  $data['endingDate']) != 1){
            return back()->withInput()->withErrors("The ending date must be bigger than starting date");
        }

        // check the ending date is bigger than starting date by 7
        $startingDate = new Carbon($data['startingDate']);
        $endingDate = new Carbon($data['endingDate']);
        if($endingDate->diff($startingDate)->days <= 7){
            return back()->withInput()->withErrors("The ending date must be bigger than starting date by 7");
        }

        //check whether student have book at this time
        $checkElement = Enrollment::where('studentId', $student['studentNum'])->get()->where('weekday',$data['weekDay'])->where('time',$data['time']);
        if(count($checkElement) >= 1){
            // the student has already had a certain class at this time
            foreach($checkElement as $row){
                $oldStartDate = $row['startDate'];
                $oldEndDate = $row['endDate'];
                $newStartDate = $data['startingDate'];
                $newEndDate = $data['endingDate'];
                // the new and old tuition period is coincident
                if(($oldStartDate < $newStartDate && $oldEndDate > $newStartDate) || ($newStartDate < $oldStartDate && $newEndDate > $oldEndDate)){
                    return back()->withInput()->withErrors("You already have had a class in this time");
                }
            }
        }

        $skillsId = \DB::table('skills')
                    ->select('id')
                    ->where('skill','=',$data['instrumentClass'])
                    ->get();

        $enrollment->studentId = $student['studentNum'];
        $enrollment->teacherId = $data['teacherNum'];
        $enrollment->skillId = $skillsId[0]->id;
        $enrollment->level = $data['level'];
        $enrollment->room = $data['room'];
        $enrollment->startDate = $data['startingDate'];
        $enrollment->endDate = $data['endingDate'];
        $enrollment->weekday = $data['weekDay'];
        $enrollment->time= $data['time'];
        $enrollment->withPermission = "1";
        $enrollment->tuitionFee =$data['tuitionFee'];

        if($enrollment->save()){
            return redirect()->back()->with('success', 'Enrol successfully');
        }else{
            return back()->withInput()->withErrors("Not successfully");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Not planned to implement

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Not planned to implement

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Not planned to implement
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Not planned to implement
    }

    /**
     * This method redirect to another static content.
     *
     * @return \Illuminate\Http\Response
     */
    public function listRec(){
        return view('lesson.list');
    }

    /**
     * This method redirect to another static content.
     *
     * @return \Illuminate\Http\Response
     */
    public function listSingingClasses(){
        return view('lesson.classes');
    }

    /**
     * This method redirect to another static content.
     *
     * @return \Illuminate\Http\Response
     */
    public function listPianoClasses(){
        return view('lesson.classespiano');
    }

    /**
     * This method redirect to another static content.
     *
     * @return \Illuminate\Http\Response
     */
    public function listDrumsClasses(){
        return view('lesson.classesdrums');
    }

    /**
     * This method redirect to another static content.
     *
     * @return \Illuminate\Http\Response
     */
    public function listMusicTheoryClasses(){
        return view('lesson.classesmusictheory');
    }

}

MusicSchool/resources/views/lesson/classes.blade.php
@extends('layouts.master')

@section('content')

    <nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <div class="navbar-brand" id="singingfirstlink">Singing Lessons</div>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
		<li><a href="#lessonformattitle">Lesson Format</a></li>
		<li><a href="#singingstylestitle">Singing Styles</a></li>
		<li><a href="#programtitle">Program and examination tutoring</a></li>
		<li><a href="#faqtitle">FAQs</a></li>
		<li><a href="#timetabletitle">Timetable</a></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<div class="row" id="top">
	        <div class="col-lg-12 jumbotron">
				<div id="singinglesson"> <img src="/resources/images/singinglesson.jpg" alt="singing lesson girl"></div>
				<br/>
				<p>What are you wainting for? Be part of our awesome singing and become an excellent singer.  We offer singing lessons in a range of styles, including Rock, R & B, Pop and Contemporary.  If you have a driving passion for music, or are just curious to see how far you can take your singing. We will help you every step of the way.  Whether you are a complete beginner, a parent seeking singing lessons for your child or a more advanced singer looking to improve further, we can help you to achieve your goals and take you to the level you want to be.</p>
				<p>Our our aim is to help you explore all your potential.  Your singing lessons will be designed to be directly relevant to your playing goals.  We know that this is key to your enjoyment and that enjoying your playing will bring greater engagement with your singing and in turn, better results!</p>
				<p>Our professional singing teachers will strive to help you achieve your goals while you grow as a musician and pianist. All of our teachers are patient, friendly and have the ability to put our students at ease and ready to learn. Play on top quality singings with experienced, encouraging teachers… request a free singing lesson.</p>
		</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2 id="lessonformattitle">Lesson Format</h2>
				<p>We offer singing lessons on a weekly or twice-weekly basis with the following appointment options:</p>
				<ul>
					<li>30, 45 or 60 minute sessions.</li>
					<li>15 minutes (for children aged 5 – 6 years only).</li>
				</ul>
				<p>During these sessions we make sure your singing lessons will be designed to be directly relevant to your playing goals.  From years of experience we know this is key to your enjoyment and will bring greater engagement with your singing and in turn, better results!</p>
			</div>
			<br/>
		</div>
		
		<p><a href="#top">Top</a></p>
		
		<div class="row">
	        <div class="col-lg-12">
				<h2 id="singingstylestitle">Singing Styles</h2>
				<p>We offer singing lessons in all styles, including:</p>
				<ul>
					<li>Classical</li>
					<li>Jazz</li>
					<li>Blues</li>
					<li>Popular & Contemporary</li>
				</ul>
			</div>
		</div>
		
		<br/>
		<p><a href="#top">Top</a></p>
		
		<div class="row">
	        <div class="col-lg-12">
				<h2 id="programtitle">Program & Examination Tutoring</h2>
				<p>If you wish to study an AMEB program, then our friendly teachers are qualified to help you prepare for your exams and give you the best chance to achieve outstanding results.</p>
				<p>We also provide coaching for other syllabi, such as the Trinity College London, ANZCA and QLD Senior Music and Music Extension.</p>
			</div>
		</div>

		<br/>
		<p><a href="#top">Top</a></p>

		<div class="row">
	        <div class="col-lg-12">
				<h2 id="faqtitle">Singing Lessons FAQs</h2>
				<h4><i><b>What length of lesson is best?</b></i></h4>
				<p>The improvement that comes with formal music lessons is largely a result of consistent and frequent interaction with your teacher/coach/mentor, and less as a result of the actual musical knowledge that is distributed to you.  For this reason, a weekly 60 minute lesson will be less effective at bringing you improvement than 2 x 30 minute lessons spread across the week.  Similarly, a weekly 60 minute lesson is not likely to yield better results than a weekly 45 minute lesson.  It is questionable that the extra 15 minutes will be of any real benefit, therefore 60 minute private lessons are generally only recommended in special cases.  For the majority of people, we recommend 45 minute lessons.  For younger children, 30 minutes is sufficient where mental fatigue is a consideration.</p>
				<p>Twice-weekly 30 or 45 minute lessons will bring great improvement.</p>
				<p>At Sono School Of Music, we will work to develop a lesson program that will optimise your results.</p>
				<h4><i><b>Do I need to do exams?</b></i></h4>
				<p>No!  We are committed to providing a highly personalised service.  We have the utmost respect for your reasons for playing, your musical preferences and your goals. In some cases, this may mean selecting a syllabus to study, in other cases not. Under guidance from your teacher, the choice is entirely yours. Keep in mind, you can study a syllabus such as AMEB classical singing AND play other things too!</p>
			</div>
			
		</div>
		
		<br/>
		<p><a href="#top">Top</a></p>

		<div class="row">
	        <div class="col-lg-12">
				<h2 id="timetabletitle">Class timetable</h2>
				<p>Here is the classes we offer in this season:</p>
				<table class="table table-striped">
					<tr>
						<th></th>
						<th>Moday</th>
						<th>Tuesday</th>
						<th>Wednesday</th>
						<th>Thursday</th>
						<th>Friday</th>
						<th>Saturday</th>
						<th>Sunday</th>
					</tr>
					<tr>
						<td>9:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>10:00</td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Singing', 'teacherNum'=>'1', 'teacherName'=>'James', 'week'=>'Tuesday', 'time'=>'10', 'tuitionFee'=>'8888')) }}">
								Classical<br>
								James.
							</a>
						</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>11:00</td>
						<td></td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Singing', 'teacherNum'=>'2', 'teacherName'=>'Hannah', 'week'=>'Wednesday', 'time'=>'11', 'tuitionFee'=>'10000')) }}">
								Classical<br>
								Hannah.
							</a>
						</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>12:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>13:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>14:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>15:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>16:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>17:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>18:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Singing', 'teacherNum'=>'2', 'teacherName'=>'Hannah', 'week'=>'Saturday', 'time'=>'18', 'tuitionFee'=>'5000')) }}">
								Classical<br>
								Hannah.
							</a>
						</td>
						<td></td>
					</tr>
				</table>
			</div>
			
		</div>
		<br/>
			<p><a href="#top">Top</a></p>
	</div>

@endsection

MusicSchool/resources/views/lesson/classesbackup.blade.php
@extends('layouts.master')

@section('content')

    <nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <div class="navbar-brand">Piano Lessons</div>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="#">Link 1</a></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<div class="row">
	        <div class="col-lg-12 jumbotron">
				<div id="photopianolesson"> <img src="/resources/images/pianolesson.jpg" alt="piano lesson girl"></div>
				<br/>
				<p>We pride ourselves on offering quality music tuition and our piano lessons are no exception.  We offer piano lessons in a range of styles, including Classical, Jazz, Blues and Popular and Contemporary.  If you have a driving passion for music, or are just curious to see how far you can take your piano playing, Sono School of Music will help you every step of the way.  Whether you are a complete beginner, a parent seeking piano lessons for your child or a more advanced player looking to improve further, we can help you to achieve your goals and take you to the level you want to be.</p>
				<p>At Sono School of Music, our our aim is for our clients gain maximum improvement from their piano lessons.  Your piano lessons will be designed to be directly relevant to your playing goals.  We know that this is key to your enjoyment and that enjoying your playing will bring greater engagement with your piano and in turn, better results!</p>
				<p>Our professional piano teachers will strive to help you achieve your goals while you grow as a musician and pianist. All of our teachers are patient, friendly and have the ability to put our students at ease and ready to learn. Play on top quality pianos with experienced, encouraging teachers… request a free piano lesson.</p>
		</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2>Lesson Format</h2>
				<p>We offer piano lessons on a weekly or twice-weekly basis with the following appointment options:</p>
				<ul>
					<li>30, 45 or 60 minute sessions.</li>
					<li>15 minutes (for children aged 5 – 6 years only).</li>
				</ul>
				<p>During these sessions we make sure your piano lessons will be designed to be directly relevant to your playing goals.  From years of experience we know this is key to your enjoyment and will bring greater engagement with your piano and in turn, better results!</p>
			</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2>Piano Styles</h2>
				<p>We offer piano lessons in all styles, including:</p>
				<ul>
					<li>Classical</li>
					<li>Jazz</li>
					<li>Blues</li>
					<li>Popular & Contemporary</li>
				</ul>
			</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2>Program & Examination Tutoring</h2>
				<p>If you wish to study an AMEB program, then our friendly teachers are qualified to help you prepare for your exams and give you the best chance to achieve outstanding results.</p>
				<p>We also provide coaching for other syllabi, such as the Trinity College London, ANZCA and QLD Senior Music and Music Extension.</p>
			</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2>Piano Lesson FAQs</h2>
				<h4><i><b>What length of lesson is best?</b></i></h4>
				<p>The improvement that comes with formal music lessons is largely a result of consistent and frequent interaction with your teacher/coach/mentor, and less as a result of the actual musical knowledge that is distributed to you.  For this reason, a weekly 60 minute lesson will be less effective at bringing you improvement than 2 x 30 minute lessons spread across the week.  Similarly, a weekly 60 minute lesson is not likely to yield better results than a weekly 45 minute lesson.  It is questionable that the extra 15 minutes will be of any real benefit, therefore 60 minute private lessons are generally only recommended in special cases.  For the majority of people, we recommend 45 minute lessons.  For younger children, 30 minutes is sufficient where mental fatigue is a consideration.</p>
				<p>Twice-weekly 30 or 45 minute lessons will bring great improvement.</p>
				<p>At Sono School Of Music, we will work to develop a lesson program that will optimise your results.</p>
				<h4><i><b>Do I need to do exams?</b></i></h4>
				<p>No!  We are committed to providing a highly personalised service.  We have the utmost respect for your reasons for playing, your musical preferences and your goals. In some cases, this may mean selecting a syllabus to study, in other cases not. Under guidance from your teacher, the choice is entirely yours. Keep in mind, you can study a syllabus such as AMEB classical piano AND play other things too!</p>
			</div>
		</div>
		<div class="row">
	        <div class="col-lg-12">
				<h2>Class timetable</h2>
				<p>Here is the classes we offer in this season:</p>
				<table class="table table-striped">
					<tr>
						<th></th>
						<th>Moday</th>
						<th>Tuesday</th>
						<th>Wednesday</th>
						<th>Thursday</th>
						<th>Friday</th>
						<th>Saturday</th>
						<th>Sunday</th>
					</tr>
					<tr>
						<td>9:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>10:00</td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Piano', 'teacherNum'=>'1', 'teacherName'=>'James', 'week'=>'Tuesday', 'time'=>'10', 'tuitionFee'=>'8888')) }}">
								Classical<br>
								James.
							</a>
						</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>11:00</td>
						<td></td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Piano', 'teacherNum'=>'2', 'teacherName'=>'Hannah', 'week'=>'Wednesday', 'time'=>'11', 'tuitionFee'=>'10000')) }}">
								Classical<br>
								Hannah.
							</a>
						</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>12:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>13:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>14:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>15:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>16:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>17:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>18:00</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>
							<a href="{{ URL::route('lesson.enrollment.create', array('class'=>'Piano', 'teacherNum'=>'2', 'teacherName'=>'Hannah', 'week'=>'Saturday', 'time'=>'18', 'tuitionFee'=>'5000')) }}">
								Classical<br>
								Hannah.
							</a>
						</td>
						<td></td>
					</tr>
				</table>
			</div>
		</div>
	</div>

@endsection