MusicSchool/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/contactus', function () {
    return view('contactus');
});

Route::get('/aboutus', function () {
    return view('aboutus');
});

// Authetication
Route::get('/login', ['as'=>'login', 'uses'=>'AuthController@login']);
Route::get('/logout', ['as'=> 'logout', 'uses'=> 'AuthController@logout']);
Route::post('/handleLogin', ['as'=>'handleLogin', 'uses'=>'AuthController@handleLogin']);

// Member Portal
Route::resource('/users', 'UserController', ['Only'=> ['create', 'store']]);
Route::get('/register', 'UserController@create');   
Route::resource('/profile/edit', 'UserController', ['Only'=> ['edit', 'update']]);

Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', ['as'=> 'home', 'uses'=> 'UserController@home']);
	Route::get('/profile', ['as'=>'profile', 'uses'=> 'UserController@profile']); 
    Route::get('/profile/edit', ['as'=>'profile', 'uses'=> 'UserController@profileEdit']);
	Route::post('handleProfileUpdate', ['as'=>'handleProfileUpdate', 'uses'=>'UserController@handleProfileUpdate']);
});

// Lesson
Route::get('/lesson', 'LessonController@listRec');
Route::get('/lesson/singingclass', 'LessonController@listSingingClasses');
Route::get('/lesson/classespiano', 'LessonController@listPianoClasses');
Route::get('/lesson/classesdrums', 'LessonController@listDrumsClasses');
Route::get('/lesson/classesmusictheory', 'LessonController@listMusicTheoryClasses');
Route::resource('/lesson/enrollment', 'LessonController',['Only'=> ['create', 'store']]);
//Route::post('/lesson/handleEnrollment', ['as'=>'handleEnrollment', 'uses'=>'LessonController@handleEnrollment']);
Route::get('/lesson/apply', ['as'=> 'apply', 'uses'=> 'UserController@applyLessons']);
Route::patch('/lesson/applyHandle/{applyHandle}', ['as'=> 'applyHandle', 'uses'=> 'UserController@applyHandle']);

// Career
Route::get('/career', 'CareerController@recruit');




// For Release 2

// student part

Route::post('/student/handleFeedback', ['as'=>'handleFeedback', 'uses'=>'UserController@handleFeedback']);
Route::get('/student/historyMarks/feedbackToTeacher', function () {
    return view('users.student.feedbackToTeacher');
});
Route::group(['middleware' => 'auth'], function() {
    Route::get('/student/hireInstrument', function () {
        return view('users.student.hireInstrument');
    });
    Route::get('/student/historyMarks', ['as'=> 'historyMarks', 'uses'=> 'UserController@historyMarks']);
    Route::resource('/student/query-instrumentlist', "InstrumentController@query");
    Route::resource('/student/query-hireInstrument', "InstrumentController@hireInstrument");
});

// teachers part
Route::get('/teachers/myTimetable', function () {
    return view('users.teacher.myTimetable');
});
Route::get('/teachers/myTimetable/timetableArrangement', function () {
    return view('users.teacher.timetableArrangement');
});
Route::get('/teacher/mailBox', function () {
    return view('users.teacher.mailBox');
});

// admin part

Route::group(['middleware' => 'auth'], function() {
    Route::get('/admin', ['as'=> 'home', 'uses'=> 'UserController@home']);
    Route::get('/admin/instrumentManagement', "AdminController@viewInstruments");
    Route::post('/admin/instrumentManagement', ['as'=> 'addNewInstruments', 'uses'=>'AdminController@addNewInstruments']);
    Route::get('/admin/lessonArrangement', function () {
        return view('users.admin.lessonArrangement');
    });
    Route::get('/admin/enrollmentArrangement', "AdminController@enrollmentArrangement");
    Route::get('/admin/enrollmentArrangement/edit', function () {
        return view('users.admin.editEnrollmentForm');
    });
    Route::get('/admin/roomArrangement', function () {
        return view('users.admin.roomArrangement');
    });
    Route::get('/admin/mailBox', function () {
        return view('users.admin.mailBox');
    });

    Route::get('/admin/crewManagement/teachers/view', 'AdminController@viewTeachers');
    Route::get('/admin/crewManagement/teachers/add', function () {
        return view('users.admin.crewManagement.teachers.add');
    });
    Route::get('/admin/crewManagement/teachers/edit', function () {
        return view('users.admin.crewManagement.teachers.edit');
    });
    Route::get('/admin/crewManagement/teachers/viewFeedback', function () {
        return view('users.admin.crewManagement.teachers.viewFeedback');
    });

    Route::get('/admin/crewManagement/students/view', 'AdminController@viewStudents');
    Route::get('/admin/crewManagement/students/add', function () {
        return view('users.admin.crewManagement.students.add');
    });
    Route::get('/admin/crewManagement/students/edit', function () {
        return view('users.admin.crewManagement.students.edit');
    });

});

// owner part
Route::get('/owner', function () {
    return view('users.owner.home');
});Route::get('/owner/mailBox', function () {
    return view('users.owner.mailBox');
});
Route::get('/owner/mailHyperlink', function () {
    return view('users.owner.mailHyperlink');
});
Route::get('/owner/makeAnnouncement', function () {
    return view('users.owner.makeAnnouncement');
});

MusicSchool/resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>
		@if(\Auth::check())
		Member Portal
		@else
		Pinelands Music School
		@endif
		</title>
		<Link rel="stylesheet prefetch" href="/resources/library/bootstrap-3.3.7-dist/css/bootstrap.css">
		<Link rel="stylesheet prefetch" href="/resources/css/frontend.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<!--<script src="/resources/library/jquery/jquery-3.1.0.min.js" crossorigin="anonymous"></script>-->
		<script src="/resources/library/bootstrap-3.3.7-dist/js/bootstrap.min.js" crossorigin="anonymous"></script> 
		<script src="/resources/library/parallax.js-1.4.2/parallax.min.js"></script>   
	</head>
	
	<body>
		
		<div id="top">

			<nav class="navbar navbar-default" style="height:100px; ">
				<div class="container-fluid">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
					<div class="navbar-header" id="logo">
						<a class="navbar-brand" href="/"><img src="/resources/images/logo.png"/></a>
					</div>
					<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/" class="navbar-menu-links">Home</a></li>
						<li><a href="/lesson" class="navbar-menu-links">Lessons</a></li>
						<li><a href="/career" class="navbar-menu-links">Careers</a></li>
						<li class="dropdown">  <a class="dropdown-toggle " data-toggle="dropdown" href="#" id="navbar-menu-dropdown-link"><span class="glyphicon glyphicon-user"></span> My Account<span class="caret"></span></a>
							<ul class="dropdown-menu"><!--dropdown menu -->
								@if(\Auth::check())
								<li> {{ link_to_route('home', 'My Portal') }} </li>
								<li role="separator" class="divider"></li>
								<li>{{ link_to_route('logout', 'Logout') }} </li>
								@else
								<li>{{link_to_route('users.create','New User')}} </li>
								<li role="separator" class="divider"></li>
								<li>{{link_to_route('login','Login')}} </li>
								@endif
							</ul><!--end of dropdown menu-->
						</li>                
					</ul><!--end of navbar ul -->
					</div><!--end of collepse-->
				</div><!-- end of navbar-->
				
			</nav>
			
		</div><!--Close div top-->
            
		@yield('content')		
		
		
		<footer class="modal-footer ">
			<ul class="nav nav-pills">
				<li><a href="/contactus" class="footer-links" id="contactus">Contact Us</a>
				<li><a href="/aboutus" class="footer-links">About Us</a>
				<li><a href="" class="footer-links">Partnership</a>
				</li>
			</ul>
			
		</div>
		<span> <img src="/resources/images/icons.png" id="social-media-icons" ></span>
	</body>
</html>